### ISSUE TITLE
does not build in Ubuntu 14.04

### ISSUE THREAD

**Issue by rgreenwood** [Esri/geocon-file-routines#1]
I get the following:

$make
gcc -c libgeocon.c
In file included from /usr/include/stdio.h:27:0,
                 from libgeocon.c:21:
/usr/include/features.h:374:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>

**Comment by rgreenwood** [comment]
src/
gcc -I../include -nostartfiles -lm -pthread -o libgeocon.so -c libgeocon.c

etc/
gcc -I../include -L../src -lgeocon -pthread -lm -o geocon_file geocon_file.c
gcc -I../include -L../src -lgeocon -pthread -lm -o geocon_cmb  geocon_cmb.c 
gcc -I../include -L../src -lgeocon -pthread -lm -o geocon_cvt  geocon_cvt.c
